
data:
  auto-save: 120 # in seconds

gg-event:
  - "&f"
  - "&3&lGGEVENT"
  - "&fGG's in the chat for a &b&lrewward&f"
  - "&f"

messages:
  prefix: "&6&lTAPMASTERS &8&l▸ &f"
  player-only: "&cThis command is player-only."
  plugin-problem: "&cThere has been a problem processing your playerdata. Reconnecting should fix it. If not, contact a developer."
  no-perm: "&cYou have no permission to do this."
  player-not-found: "&cThis player never joined our server."
  player-not-online: "&cThis player is not currently online."
  not-enough-clicks: "&cYou need at least 10 clicks to sell them."
  sell-clicks:
    - ""
    - "&a&lSELLCLICKS"
    - "&a&lSOLD &f{click} &a&lFOR $&f{money} &7(( &cx&f{multi} &7))"
    - ""
  invalid-currency: "&cInvalid currency. &eCurrencies: click, money, gem, token, prestige_point"
  invalid-number: "&cThe number must be more than -1"
  invalid-booster-type: "&cThe booster's  type should either be global or personal."
  invalid-multiplier: "&cMultiplier must be greater than 1 and in a format like this: 1.5"
  invalid-timer: "&cThe timer must be given in seconds, and greater than 0."
  given-booster: "&fYou successfully gave a {currency} &fbooster to {player}&f."
  got-booster: "&fYou &aGOT &fa {currency} &fbooster!"
  got-infinite-booster: "&fYou &aGOT &fan infinite booster!"
  admin-give: "&fYou just gave &e{num} {currency} &fto &e{player}"
  admin-take: "&fYou just took &e{num} {currency} &ffrom &e{player}"
  admin-set: "&fYou just set &e{player}&f's {currency} &fto &e{num}"
  wrong-number: "&cThe player cant go out of the minimum, and maximum limit."
  boosters:
    - ""
    - "&b&l{player}'s boosters"
    - "{boosters}"
    - ""
    - "&6&lGlobal Booster"
    - "{global}"
    - ""
  profile:
    - ""
    - "&b&l{player}'s profile"
    - ""
    - "&fClicks: &7{clicks}"
    - "&fRaw Clicks: &7{raw_clicks}"
    - "&fMoney: &7{money}"
    - "&fGems: &7{gem}"
    - "&fTokens: &7{token}"
    - "&fPrestige: &7{prestige}"
    - "&fPrestige Points: &7{prestige_point}"
    - ""
  help:
    - ""
    - "&6&lTAPMASTERS"
    - ""
    - "&f/tapmasters help"
    - "&f/account [player] &8- &f/profile [player]"
    - "&f/booster &8- &f/boosters"
    - ""
    - "&f/tapmasters admin"
    - ""
  help-admin:
    - ""
    - "&6&lTAPMASTERS &f- &cAdmin"
    - ""
    - "&eCurrencies: click, money, gem, token, prestige_point"
    - "&f/tapmasters admin"
    - "&f/tapmasters admin give <player> <currency> <amount>"
    - "&f/tapmasters admin take <player> <currency> <amount>"
    - "&f/tapmasters admin set <player> <currency> <amount>"
    - "&f/tapmasters admin boosters <player>"
    - ""
    - "&f/booster give <player> <personal/global> <currency> <multiplier> <seconds>"
    - "&f/booster start <currency> <multiplier> <seconds> - global booster"
    - ""
    - "&f/ggevent start"
    - ""